### ISSUE TITLE
Move to todotxt organization

### ISSUE THREAD

**Issue by karbassi** [rpdillon/todotxt.el#19]
Hello @rpdillon  

There's a new organization (@todotxt) managing the `todo.txt` format, `todo.txt-cli`, and other apps. It'd be great to move this repo there and get more group maintenance. 

**Would you be willing to move this project over and join the team to manage your repo, with the help of others?**

It's better to move it than fork it since the issues, wiki, and history will all move along with it.

**Comment by rpdillon** [comment]
Sure!  Forking is a less compelling option.  I haven't been actively maintaining as much as I would like, so pulling this under the @todotxt umbrella sounds good.  Shall I initiate a transfer?

**Comment by rpdillon** [comment]
Closing due to lack of response.

**Comment by karbassi** [comment]
@rpdillon this fell off my radar; deeply sorry.

To move it under the @todotxt org, you have to just [transfer ownership](https://help.github.com/en/github/administering-a-repository/transferring-a-repository). Tell me if you'd like to do that and I'll add you to the org.
