### ISSUE TITLE
Manual reordering of tasks

### ISSUE THREAD

**Issue by vibrog** [rpdillon/todotxt.el#22]
I'd like to have shortcuts to move the currently highlighted tasks up or down.
Similar to [move-text](https://github.com/emacsfodder/move-text).

**Comment by ComedyTomedy** [comment]
The functionality already exists. Bind `todotxt-transpose-lines-up` / `-down`. For example, using `use-package` you could load `todotxt-mode` like this:

    (use-package todotxt
      :bind
      ("C-c t" . todotxt)
      (:map todotxt-mode-map
        ("M-<up>" . todotxt-transpose-lines-up)
        ("M-<down>" . todotxt-transpose-lines-down)))

**Comment by ComedyTomedy** [comment]
Sorry! I've just realised this was implemented since your comment.

It probably makes sense to include "M-<up>"/"M-<down>" as default keys, but otherwise I guess this issue could be closed.

**Comment by vibrog** [comment]
Thanks, exactly the functionality I asked for.
