### ISSUE TITLE
http://www.killring.org/todotxtel looks very weird

### ISSUE THREAD

**Issue by xuchunyang** [rpdillon/todotxt.el#24]
Here is a screenshot using Safari, other web browsers like Chrome and EWW look the same

![screen shot 2019-01-05 at 1 41 38 pm](https://user-images.githubusercontent.com/4550353/50720843-00047b80-10f0-11e9-9a3b-fad01f8d9ca4.png)

**Comment by rpdillon** [comment]
Thanks for reporting, this is fixed now.
