### ISSUE TITLE
paging rpdillon re: redbean TiddlyWiki

### ISSUE THREAD

**Issue by shmup** [rpdillon/todotxt.el#38]
Couldn't find a way to contact ya. Justine (jart) shared your [redbean twiddlywiki project](https://rpdillon.net/redbean-tiddlywiki-saver.html), wondering if they broke it when putting `StoreAsset` behind a flag.

> Does anyone here know the author so we can help improve the example code so we can make sure it works for people?

If you have a method of preferred contact, cool, but alternatively pop into the redbean discord if ya want.

https://discord.gg/A8uKKWbfnB

**Comment by rpdillon** [comment]
Thanks for the head's up, I still use Tiddlywiki regularly, so I'll take a look.  I haven't used redbean for this lately, but I was just emailing Jart about the DNS resolution for redbean.dev three weeks ago, and we had a brief interchange there. I've been meaning to improve my prototype from that post. I'll add it to my list to take a look at this weekend.

There were other issues with the implementation in that post (related to file sizes as the wiki grows) that I never addressed, so I bundle those to projects together. Thanks for flagging.
