### ISSUE TITLE
Managing dates and deadlines

### ISSUE THREAD

**Issue by samspo** [rpdillon/todotxt.el#9]
(as you are working on this program...)

Allow to add and filter due dates with format due:XXX-XX-XX (to permit compatibility with https://play.google.com/store/apps/details?id=nl.mpcjanssen.todotxtholo)

**Comment by rpdillon** [comment]
I've added support for adding and editing due dates on master which should be compatible with SimpleTask.  Filtering will come in a later commit.  Closing for now.
